spring.application.name=tp

# Deshabilita el auto-configure de MongoDB mientras se usa persistencia en memoria
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
# MongoDB
spring.data.mongodb.uri=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/tacs?authSource=admin
spring.data.mongodb.database=tacs